name: Deploy using Github

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: npm install
        run: npm install
        env:
          CI: true

  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          appdir: ./backend
          heroku_api_key: ${{secrets.API_KEY}}
          heroku_app_name: "timetable-backend" #Must be unique in Heroku
          heroku_email: ${{secrets.API_EMAIL}}

  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.API_KEY}}
          heroku_app_name: "timetable-it-proj" #Must be unique in Heroku
          heroku_email: ${{secrets.API_EMAIL}}
